sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t quentic/rpi-ruby-raspbian .
# test image
- docker run quentic/rpi-ruby-raspbian ruby --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "version=" Dockerfile  | sed "s/[^0-9]*\([0-9.]*\).*/\1/")
    docker tag quentic/rpi-ruby-raspbian  quentin/ruby-raspbian-arm:$TAG
    docker push quentic/rpi-ruby-raspbian:$TAG
    docker push quentic/rpi-ruby-raspbian
  fi
